// AUTO-GENERATED by scripts/gen-world-dotmap.mjs — do not edit by hand.
// Dotted map: /home/world-dots.svg. Beacons projected onto real Corneroom cities.
export const WORLD_ASPECT = 1.9833;
export type Beacon = { name: string; left: number; top: number; featured: boolean };
export const WORLD_BEACONS: Beacon[] = [
  {
    "name": "London",
    "left": 49.58,
    "top": 24.537,
    "featured": true
  },
  {
    "name": "New York",
    "left": 28.151,
    "top": 34.641,
    "featured": true
  },
  {
    "name": "Hanoi",
    "left": 81.513,
    "top": 47.631,
    "featured": true
  },
  {
    "name": "Chiang Mai",
    "left": 79.412,
    "top": 49.075,
    "featured": true
  },
  {
    "name": "Lagos",
    "left": 51.261,
    "top": 56.292,
    "featured": true
  },
  {
    "name": "Lisbon",
    "left": 47.059,
    "top": 36.084,
    "featured": false
  },
  {
    "name": "Berlin",
    "left": 53.782,
    "top": 24.537,
    "featured": false
  },
  {
    "name": "Split",
    "left": 55.042,
    "top": 31.754,
    "featured": false
  },
  {
    "name": "Mexico City",
    "left": 20.588,
    "top": 49.075,
    "featured": false
  },
  {
    "name": "Toronto",
    "left": 26.471,
    "top": 31.754,
    "featured": false
  },
  {
    "name": "Los Angeles",
    "left": 15.126,
    "top": 38.971,
    "featured": false
  },
  {
    "name": "Paris",
    "left": 50.42,
    "top": 27.424,
    "featured": false
  },
  {
    "name": "Rome",
    "left": 53.782,
    "top": 33.198,
    "featured": false
  },
  {
    "name": "Stockholm",
    "left": 55.042,
    "top": 17.321,
    "featured": false
  },
  {
    "name": "Dubai",
    "left": 66.387,
    "top": 44.745,
    "featured": false
  },
  {
    "name": "Mumbai",
    "left": 71.849,
    "top": 49.075,
    "featured": false
  },
  {
    "name": "Bangkok",
    "left": 80.252,
    "top": 51.962,
    "featured": false
  },
  {
    "name": "Tokyo",
    "left": 91.176,
    "top": 37.528,
    "featured": false
  },
  {
    "name": "Seoul",
    "left": 87.395,
    "top": 36.084,
    "featured": false
  },
  {
    "name": "Bali",
    "left": 84.034,
    "top": 64.952,
    "featured": false
  },
  {
    "name": "Singapore",
    "left": 80.672,
    "top": 59.178,
    "featured": false
  },
  {
    "name": "Sydney",
    "left": 95.378,
    "top": 80.829,
    "featured": false
  },
  {
    "name": "São Paulo",
    "left": 35.714,
    "top": 75.056,
    "featured": false
  },
  {
    "name": "Cape Town",
    "left": 55.882,
    "top": 80.829,
    "featured": false
  },
  {
    "name": "Nairobi",
    "left": 60.924,
    "top": 60.622,
    "featured": false
  }
];
